CREATE TABLE public.persons(
	created_by integer NOT NULL DEFAULT __current_user(),
	created_date timestamp without time zone NOT NULL DEFAULT timezone('UTC'::text, now()),
	modified_by integer NULL,
	modified_date timestamp without time zone NULL,
	deleted boolean NOT NULL DEFAULT false,
	deleted_by integer NULL,
	deleted_date timestamp without time zone NULL,
	id integer NOT NULL DEFAULT nextval('persons_id_seq'::regclass),
	id_person_type integer NOT NULL,
	id_org integer NULL,
	first_name character varying NOT NULL,
	last_name character varying NOT NULL,
	email character varying NOT NULL,
	dob date NULL,
	id_gender integer NULL,
	address1 character varying NULL,
	address2 character varying NULL,
	city character varying NULL,
	zip character varying NULL,
	id_state integer NULL,
	id_country integer NULL,
	id_time_zone integer NOT NULL DEFAULT 21,
	CONSTRAINT pk_persons PRIMARY KEY (id),
	CONSTRAINT ak_person_email UNIQUE (email),
	CONSTRAINT fk_person_person_type_pk FOREIGN KEY (id_person_type) REFERENCES public.person_types (id),
	CONSTRAINT fk_person_organizatin_pk FOREIGN KEY (id_org) REFERENCES public.organizations (id),
	CONSTRAINT fk_person_state_pk FOREIGN KEY (id_state) REFERENCES public.states (id),
	CONSTRAINT fk_person_country_pk FOREIGN KEY (id_country) REFERENCES public.countries (id),
	CONSTRAINT fk_person_gender_pk FOREIGN KEY (id_gender) REFERENCES public.genders (id),
	CONSTRAINT fk_timezone_persons FOREIGN KEY (id_time_zone) REFERENCES public.time_zones (id) 
	)
	